# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, to='adoptions.Vaccine'),
        ),
    ]
